import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#a33e00",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#9ccaff",
        "surface-dim": "#dadad4",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed-variant": "#474746",
        "error": "#ba1a1a",
        "surface-container-low": "#f4f4ed",
        "on-primary-fixed": "#360f00",
        "on-primary-fixed-variant": "#7c2e00",
        "on-tertiary-fixed-variant": "#00497b",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001d35",
        "surface-container-high": "#e8e9e2",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#1a1c18",
        "tertiary-fixed": "#d0e4ff",
        "inverse-primary": "#ffb596",
        "outline-variant": "#e3bfb1",
        "primary": "#a33e00",
        "on-primary-container": "#561d00",
        "on-secondary-fixed": "#1b1c1c",
        "secondary": "#5f5e5e",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1ea",
        "surface-bright": "#fafaf3",
        "primary-fixed-dim": "#ffb596",
        "primary-container": "#ff6600",
        "background": "#fafaf3",
        "on-secondary-container": "#636262",
        "outline": "#8e7164",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5a4136",
        "surface": "#fafaf3",
        "tertiary": "#0062a1",
        "surface-container": "#eeeee7",
        "surface-container-highest": "#e3e3dc",
        "tertiary-container": "#009cfc",
        "surface-variant": "#e3e3dc",
        "inverse-surface": "#2f312d",
        "on-background": "#1a1c18",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#003155",
        "primary-fixed": "#ffdbcd",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;